# Generated by Django 5.1.3 on 2025-03-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_recycler_tbl_category_ward_wastethreshold_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recycler',
        ),
    ]
