# Generated by Django 5.1.3 on 2025-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pswd', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('utype', models.CharField(default='user', max_length=100)),
            ],
        ),
    ]
