# Generated by Django 5.1.7 on 2025-03-28 10:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('driverapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('utype', models.CharField(default='user', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=20)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('bin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bin_status', models.CharField(choices=[('not_placed', 'Not Placed'), ('placed', 'Placed')], default='not_placed', max_length=20)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driverapp.driverregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('incompleted', 'Incompleted')], default='pending', max_length=20)),
                ('categories', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('cash', 'Cash'), ('card_payment', 'Card Payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cash', 'Cash'), ('card_payment', 'Card Payment')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=10, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_card', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
                ('waste_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.wastesubmission')),
            ],
        ),
    ]
