# Generated by Django 5.1.3 on 2025-02-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_complaintregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintregister',
            name='bin_request_image',
        ),
    ]
