# Generated by Django 5.1.3 on 2025-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_complaintregister_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintregister',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
