# Generated by Django 5.1.3 on 2025-02-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0002_driverregister_place'),
        ('userapp', '0007_alter_complaintregister_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregister',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driverapp.driverregister'),
        ),
    ]
