# Generated by Django 5.1.3 on 2025-02-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_complaintregister_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregister',
            name='bin_status',
            field=models.CharField(choices=[('not_placed', 'Not Placed'), ('placed', 'Placed')], default='not_placed', max_length=20),
        ),
    ]
