# Generated by Django 5.1.3 on 2025-03-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_tbl_register_latitude_tbl_register_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintregister',
            name='ward',
        ),
    ]
