# Generated by Django 5.1.7 on 2025-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_complaintregister_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintregister',
            name='location',
        ),
        migrations.AddField(
            model_name='complaintregister',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintregister',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
